matrix:
  include:
    - language: dart
      sudo: false
      dart: stable
      dist: trusty
      install_dartium: true
      script:
        - pub get && pub run test --platform dartium test/


    - language: java
      jdk: oraclejdk8
      sudo: false
      before_install:
        - cd $TRAVIS_BUILD_DIR/DataStructures/DataStructuresJava
      script:
        - mvn clean verify